# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy.

To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook.

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicants_data_df = pd.read_csv(Path("/content/applicants_data.csv"))

# Review the DataFrame

applicants_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns

applicants_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicants_data = applicants_data_df.drop(columns = ["EIN", "NAME"])

# Review the DataFrame

applicants_data.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables
categorical_variables = ["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "SPECIAL_CONSIDERATIONS"]

# Display the categorical variables list

categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# View the 'INCOME_AMT' column

applicants_data['INCOME_AMT'].value_counts()

0                24388
25000-99999       3747
100000-499999     3374
1M-5M              955
1-9999             728
10000-24999        543
10M-50M            240
5M-10M             185
50M+               139
Name: INCOME_AMT, dtype: int64

In [7]:
## modify INCOME_AMT !!!!!!!!

applicants_data.loc[applicants_data['INCOME_AMT'] == '0', 'INCOME_AMT'] = '0'
applicants_data.loc[applicants_data['INCOME_AMT'] == '25000-99999', 'INCOME_AMT'] = '50000'
applicants_data.loc[applicants_data['INCOME_AMT'] == '100000-499999', 'INCOME_AMT'] = '300000'
applicants_data.loc[applicants_data['INCOME_AMT'] == '1M-5M', 'INCOME_AMT'] = '3000000'
applicants_data.loc[applicants_data['INCOME_AMT'] == '1-9999', 'INCOME_AMT'] = '5000'
applicants_data.loc[applicants_data['INCOME_AMT'] == '10000-24999', 'INCOME_AMT'] = '17500'
applicants_data.loc[applicants_data['INCOME_AMT'] == '10M-50M', 'INCOME_AMT'] = '30000000'
applicants_data.loc[applicants_data['INCOME_AMT'] == '5M-10M', 'INCOME_AMT'] = '7500000'
applicants_data.loc[applicants_data['INCOME_AMT'] == '50M+', 'INCOME_AMT'] = '50000000'

applicants_data.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,5000,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,17500,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,300000,N,142590,1

In [8]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [9]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicants_data[categorical_variables])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [11]:
# Create a DataFrame with the encoded variables

encoded_df = pd.DataFrame(encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame

encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [12]:
applicants_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [13]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame

numerical_variables = applicants_data[['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL']]

encoded_applicants = pd.concat([encoded_df, numerical_variables], axis=1)
encoded_applicants.dropna(inplace=True)

# Review the Dataframe

encoded_applicants.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1,142590,1

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [15]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_applicants["IS_SUCCESSFUL"]

# Display a sample of y

y.head()

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [16]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_applicants.drop(columns = "IS_SUCCESSFUL")

# Review the features DataFrame

X.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1,142590

### Step 6: Split the features and target sets into training and testing datasets.

In [17]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [18]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [19]:
# Define the the number of inputs (features) to the model
number_input_features = 107

# Review the number of features
number_input_features

107

In [20]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [21]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  72

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

72

In [22]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 36

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

36

In [23]:
# Create the Sequential model instance
nn = Sequential()

In [24]:
# Add the first hidden layer
nn.add(
    Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

In [25]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [26]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="linear"))

In [27]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 72)                7776

 dense_1 (Dense)             (None, 36)                2628

 dense_2 (Dense)             (None, 1)                 37

=================================================================
Total params: 10,441
Trainable params: 10,441
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [28]:
# Compile the Sequential model

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [29]:
# Fit the model using 50 epochs and the training data

model = nn.fit(X, y, validation_split=0.3, epochs=50)

Epoch 1/50
751/751 [==============================] - 4s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 2/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 3/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 4/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 5/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 6/50
751/751 [==============================] - 3s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 7/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 8/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 9/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 10/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 11/50
751/751 [==============================] - 3s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 12/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 13/50
751/751 [==============================] - 3s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 14/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 15/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 16/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 17/50
751/751 [==============================] - 3s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 18/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 19/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 20/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 21/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 22/50
751/751 [==============================] - 3s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 23/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 24/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 25/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 26/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9605 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 27/50
751/751 [==============================] - 2s 2ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 28/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 29/50
751/751 [==============================] - 3s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 30/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 31/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 32/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 33/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 34/50
751/751 [==============================] - 3s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 35/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 36/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 37/50
751/751 [==============================] - 2s 2ms/step - loss: 6.9605 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 38/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 39/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 40/50
751/751 [==============================] - 3s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 41/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 42/50
751/751 [==============================] - 2s 2ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 43/50
751/751 [==============================] - 3s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 44/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 45/50
751/751 [==============================] - 2s 2ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 46/50
751/751 [==============================] - 3s 4ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 47/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 48/50
751/751 [==============================] - 2s 2ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 49/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064
Epoch 50/50
751/751 [==============================] - 2s 3ms/step - loss: 6.9606 - accuracy: 0.5435 - val_loss: 7.5268 - val_accuracy: 0.5064

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [30]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 3.3670 - accuracy: 0.4805 - 446ms/epoch - 2ms/step
Loss: 3.367025852203369, Accuracy: 0.48046648502349854

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [31]:
# Set the model's file path

file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file

nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [32]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

107

In [33]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [34]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 107

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

107

In [35]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer2_A1 = 54

# Review the number of hidden nodes in the first layer
hidden_nodes_layer2_A1

54

In [36]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [37]:
# First hidden layer

nn_A1.add(
    Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model

nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 72)                7776

 dense_4 (Dense)             (None, 1)                 73

=================================================================
Total params: 7,849
Trainable params: 7,849
Non-trainable params: 0
_________________________________________________________________

In [38]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [39]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X, y, validation_split=0.3, epochs=50)

Epoch 1/50
751/751 [==============================] - 3s 3ms/step - loss: 12843.5439 - accuracy: 0.5006 - val_loss: 7117.5859 - val_accuracy: 0.5064
Epoch 2/50
751/751 [==============================] - 2s 2ms/step - loss: 14525.1611 - accuracy: 0.5165 - val_loss: 75323.5625 - val_accuracy: 0.4936
Epoch 3/50
751/751 [==============================] - 3s 3ms/step - loss: 12884.1924 - accuracy: 0.4999 - val_loss: 23269.2812 - val_accuracy: 0.4936
Epoch 4/50
751/751 [==============================] - 2s 3ms/step - loss: 9369.1758 - accuracy: 0.5235 - val_loss: 312.3009 - val_accuracy: 0.5064
Epoch 5/50
751/751 [==============================] - 2s 2ms/step - loss: 16795.0859 - accuracy: 0.4946 - val_loss: 85905.1172 - val_accuracy: 0.4936
Epoch 6/50
751/751 [==============================] - 2s 3ms/step - loss: 17998.6387 - accuracy: 0.4969 - val_loss: 2519.2483 - val_accuracy: 0.5064
Epoch 7/50
751/751 [==============================] - 2s 3ms/step - loss: 12155.8818 - accuracy: 0.5085 - val_loss: 88517.7266 - val_accuracy: 0.4936
Epoch 8/50
751/751 [==============================] - 2s 2ms/step - loss: 9720.9551 - accuracy: 0.5055 - val_loss: 116242.0000 - val_accuracy: 0.5064
Epoch 9/50
751/751 [==============================] - 2s 3ms/step - loss: 3436.0461 - accuracy: 0.5362 - val_loss: 4990.5264 - val_accuracy: 0.5722
Epoch 10/50
751/751 [==============================] - 2s 3ms/step - loss: 8425.3125 - accuracy: 0.5300 - val_loss: 4802.9844 - val_accuracy: 0.5841
Epoch 11/50
751/751 [==============================] - 2s 3ms/step - loss: 9053.5576 - accuracy: 0.5266 - val_loss: 976.8676 - val_accuracy: 0.5201
Epoch 12/50
751/751 [==============================] - 2s 2ms/step - loss: 11492.0078 - accuracy: 0.5221 - val_loss: 36697.9336 - val_accuracy: 0.4936
Epoch 13/50
751/751 [==============================] - 2s 3ms/step - loss: 7740.3169 - accuracy: 0.5370 - val_loss: 50229.7188 - val_accuracy: 0.5064
Epoch 14/50
751/751 [==============================] - 2s 2ms/step - loss: 6378.4912 - accuracy: 0.5343 - val_loss: 1512.8539 - val_accuracy: 0.5113
Epoch 15/50
751/751 [==============================] - 2s 3ms/step - loss: 7118.4194 - accuracy: 0.5447 - val_loss: 88340.4062 - val_accuracy: 0.4936
Epoch 16/50
751/751 [==============================] - 3s 3ms/step - loss: 8219.6074 - accuracy: 0.5439 - val_loss: 36708.5234 - val_accuracy: 0.4936
Epoch 17/50
751/751 [==============================] - 2s 3ms/step - loss: 5667.5396 - accuracy: 0.5859 - val_loss: 52622.1250 - val_accuracy: 0.4936
Epoch 18/50
751/751 [==============================] - 2s 2ms/step - loss: 12379.7207 - accuracy: 0.5310 - val_loss: 78314.2344 - val_accuracy: 0.4936
Epoch 19/50
751/751 [==============================] - 2s 3ms/step - loss: 7174.1582 - accuracy: 0.5076 - val_loss: 174071.6719 - val_accuracy: 0.5064
Epoch 20/50
751/751 [==============================] - 2s 3ms/step - loss: 12485.9512 - accuracy: 0.5114 - val_loss: 51824.7969 - val_accuracy: 0.4936
Epoch 21/50
751/751 [==============================] - 2s 2ms/step - loss: 7766.4971 - accuracy: 0.5317 - val_loss: 16976.2227 - val_accuracy: 0.6145
Epoch 22/50
751/751 [==============================] - 3s 3ms/step - loss: 2487.1567 - accuracy: 0.5632 - val_loss: 52980.4453 - val_accuracy: 0.4936
Epoch 23/50
751/751 [==============================] - 2s 3ms/step - loss: 1521.3813 - accuracy: 0.5673 - val_loss: 7983.3984 - val_accuracy: 0.6004
Epoch 24/50
751/751 [==============================] - 2s 3ms/step - loss: 4913.1025 - accuracy: 0.5635 - val_loss: 175475.2344 - val_accuracy: 0.5064
Epoch 25/50
751/751 [==============================] - 2s 2ms/step - loss: 5639.9722 - accuracy: 0.5788 - val_loss: 10126.6768 - val_accuracy: 0.6277
Epoch 26/50
751/751 [==============================] - 2s 3ms/step - loss: 5619.8730 - accuracy: 0.5820 - val_loss: 183.3491 - val_accuracy: 0.6128
Epoch 27/50
751/751 [==============================] - 2s 3ms/step - loss: 8889.7363 - accuracy: 0.5699 - val_loss: 1192.1663 - val_accuracy: 0.6114
Epoch 28/50
751/751 [==============================] - 3s 4ms/step - loss: 6768.5146 - accuracy: 0.5444 - val_loss: 620.1196 - val_accuracy: 0.6005
Epoch 29/50
751/751 [==============================] - 2s 3ms/step - loss: 7085.5981 - accuracy: 0.5894 - val_loss: 18900.9375 - val_accuracy: 0.5064
Epoch 30/50
751/751 [==============================] - 2s 3ms/step - loss: 4623.9092 - accuracy: 0.5528 - val_loss: 30975.9648 - val_accuracy: 0.4936
Epoch 31/50
751/751 [==============================] - 2s 3ms/step - loss: 3623.7991 - accuracy: 0.5937 - val_loss: 52775.9531 - val_accuracy: 0.5064
Epoch 32/50
751/751 [==============================] - 2s 2ms/step - loss: 3367.8157 - accuracy: 0.5623 - val_loss: 6660.7617 - val_accuracy: 0.6349
Epoch 33/50
751/751 [==============================] - 2s 3ms/step - loss: 3531.0618 - accuracy: 0.5848 - val_loss: 1710.8457 - val_accuracy: 0.6219
Epoch 34/50
751/751 [==============================] - 3s 4ms/step - loss: 4493.0679 - accuracy: 0.5878 - val_loss: 8161.0542 - val_accuracy: 0.5418
Epoch 35/50
751/751 [==============================] - 2s 3ms/step - loss: 5998.5107 - accuracy: 0.5702 - val_loss: 19508.1777 - val_accuracy: 0.4936
Epoch 36/50
751/751 [==============================] - 2s 2ms/step - loss: 473.4861 - accuracy: 0.6343 - val_loss: 1397.1412 - val_accuracy: 0.6388
Epoch 37/50
751/751 [==============================] - 2s 3ms/step - loss: 3301.6433 - accuracy: 0.5598 - val_loss: 15024.8896 - val_accuracy: 0.5079
Epoch 38/50
751/751 [==============================] - 2s 3ms/step - loss: 2928.0715 - accuracy: 0.6040 - val_loss: 69945.8516 - val_accuracy: 0.5064
Epoch 39/50
751/751 [==============================] - 2s 2ms/step - loss: 1702.6794 - accuracy: 0.5959 - val_loss: 488.5290 - val_accuracy: 0.6299
Epoch 40/50
751/751 [==============================] - 2s 3ms/step - loss: 4926.7866 - accuracy: 0.5275 - val_loss: 6758.4795 - val_accuracy: 0.6143
Epoch 41/50
751/751 [==============================] - 2s 3ms/step - loss: 2572.0718 - accuracy: 0.5587 - val_loss: 16774.7676 - val_accuracy: 0.4936
Epoch 42/50
751/751 [==============================] - 2s 3ms/step - loss: 1581.1930 - accuracy: 0.5772 - val_loss: 22558.1172 - val_accuracy: 0.5064
Epoch 43/50
751/751 [==============================] - 2s 3ms/step - loss: 1494.3296 - accuracy: 0.5806 - val_loss: 21822.0645 - val_accuracy: 0.5064
Epoch 44/50
751/751 [==============================] - 2s 3ms/step - loss: 2420.2942 - accuracy: 0.5762 - val_loss: 14153.7061 - val_accuracy: 0.4936
Epoch 45/50
751/751 [==============================] - 2s 3ms/step - loss: 2801.6670 - accuracy: 0.5744 - val_loss: 11421.0928 - val_accuracy: 0.5066
Epoch 46/50
751/751 [==============================] - 2s 3ms/step - loss: 1098.7664 - accuracy: 0.5620 - val_loss: 51272.6289 - val_accuracy: 0.5064
Epoch 47/50
751/751 [==============================] - 2s 3ms/step - loss: 2138.4824 - accuracy: 0.5573 - val_loss: 9233.8057 - val_accuracy: 0.5064
Epoch 48/50
751/751 [==============================] - 2s 3ms/step - loss: 942.6628 - accuracy: 0.6054 - val_loss: 21461.6621 - val_accuracy: 0.4936
Epoch 49/50
751/751 [==============================] - 2s 2ms/step - loss: 2076.7510 - accuracy: 0.5485 - val_loss: 12681.4170 - val_accuracy: 0.4936
Epoch 50/50
751/751 [==============================] - 2s 3ms/step - loss: 1621.3719 - accuracy: 0.5703 - val_loss: 4620.4639 - val_accuracy: 0.6131

#### Alternative Model 2

In [40]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

107

In [41]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [65]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = number_input_features/2


# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

53.5

In [52]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [67]:
# First hidden layer


nn_A2.add(
    Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# adding a second hidden layer

nn_A2.add(
    Dense(units=hidden_nodes_layer2, activation="relu")
)

# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model

nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_11 (Dense)            (None, 72)                7776

 dense_12 (Dense)            (None, 1)                 73

 dense_13 (Dense)            (None, 72)                144

 dense_14 (Dense)            (None, 1)                 73

 dense_15 (Dense)            (None, 72)                144

 dense_16 (Dense)            (None, 36)                2628

 dense_17 (Dense)            (None, 1)                 37

 dense_18 (Dense)            (None, 72)                144

 dense_19 (Dense)            (None, 36)                2628

 dense_20 (Dense)            (None, 1)                 37

=================================================================
Total params: 13,684
Trainable params: 13,684
Non-trainable params: 0
_________________________________________________________________

In [68]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [69]:
# Fit the model
fit_model_A2 = nn_A2.fit(X, y, validation_split=0.3, epochs= 80)

Epoch 1/80
751/751 [==============================] - 5s 4ms/step - loss: 0.6898 - accuracy: 0.5435 - val_loss: 0.6961 - val_accuracy: 0.5064
Epoch 2/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6896 - accuracy: 0.5435 - val_loss: 0.6951 - val_accuracy: 0.5064
Epoch 3/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6896 - accuracy: 0.5435 - val_loss: 0.6963 - val_accuracy: 0.5064
Epoch 4/80
751/751 [==============================] - 3s 5ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6947 - val_accuracy: 0.5064
Epoch 5/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6954 - val_accuracy: 0.5064
Epoch 6/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6951 - val_accuracy: 0.5064
Epoch 7/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 8/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6960 - val_accuracy: 0.5064
Epoch 9/80
751/751 [==============================] - 3s 5ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 10/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6947 - val_accuracy: 0.5064
Epoch 11/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6957 - val_accuracy: 0.5064
Epoch 12/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6964 - val_accuracy: 0.5064
Epoch 13/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6954 - val_accuracy: 0.5064
Epoch 14/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6965 - val_accuracy: 0.5064
Epoch 15/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 16/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6960 - val_accuracy: 0.5064
Epoch 17/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6966 - val_accuracy: 0.5064
Epoch 18/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6962 - val_accuracy: 0.5064
Epoch 19/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6949 - val_accuracy: 0.5064
Epoch 20/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6949 - val_accuracy: 0.5064
Epoch 21/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6978 - val_accuracy: 0.5064
Epoch 22/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6961 - val_accuracy: 0.5064
Epoch 23/80
751/751 [==============================] - 4s 5ms/step - loss: 0.6893 - accuracy: 0.5435 - val_loss: 0.6974 - val_accuracy: 0.5064
Epoch 24/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6968 - val_accuracy: 0.5064
Epoch 25/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6953 - val_accuracy: 0.5064
Epoch 26/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6951 - val_accuracy: 0.5064
Epoch 27/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 28/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6947 - val_accuracy: 0.5064
Epoch 29/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6949 - val_accuracy: 0.5064
Epoch 30/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 31/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6965 - val_accuracy: 0.5064
Epoch 32/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6954 - val_accuracy: 0.5064
Epoch 33/80
751/751 [==============================] - 3s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6953 - val_accuracy: 0.5064
Epoch 34/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6949 - val_accuracy: 0.5064
Epoch 35/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 36/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6895 - accuracy: 0.5435 - val_loss: 0.6961 - val_accuracy: 0.5064
Epoch 37/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6971 - val_accuracy: 0.5064
Epoch 38/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6947 - val_accuracy: 0.5064
Epoch 39/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6964 - val_accuracy: 0.5064
Epoch 40/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6953 - val_accuracy: 0.5064
Epoch 41/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6951 - val_accuracy: 0.5064
Epoch 42/80
751/751 [==============================] - 4s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6962 - val_accuracy: 0.5064
Epoch 43/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6971 - val_accuracy: 0.5064
Epoch 44/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6953 - val_accuracy: 0.5064
Epoch 45/80
751/751 [==============================] - 4s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6955 - val_accuracy: 0.5064
Epoch 46/80
751/751 [==============================] - 9s 12ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6966 - val_accuracy: 0.5064
Epoch 47/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 48/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 49/80
751/751 [==============================] - 4s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6955 - val_accuracy: 0.5064
Epoch 50/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6958 - val_accuracy: 0.5064
Epoch 51/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6958 - val_accuracy: 0.5064
Epoch 52/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6963 - val_accuracy: 0.5064
Epoch 53/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6962 - val_accuracy: 0.5064
Epoch 54/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6958 - val_accuracy: 0.5064
Epoch 55/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6965 - val_accuracy: 0.5064
Epoch 56/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6955 - val_accuracy: 0.5064
Epoch 57/80
751/751 [==============================] - 7s 9ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6955 - val_accuracy: 0.5064
Epoch 58/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6957 - val_accuracy: 0.5064
Epoch 59/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6954 - val_accuracy: 0.5064
Epoch 60/80
751/751 [==============================] - 3s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6955 - val_accuracy: 0.5064
Epoch 61/80
751/751 [==============================] - 5s 6ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6961 - val_accuracy: 0.5064
Epoch 62/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6958 - val_accuracy: 0.5064
Epoch 63/80
751/751 [==============================] - 4s 6ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 64/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6952 - val_accuracy: 0.5064
Epoch 65/80
751/751 [==============================] - 4s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6958 - val_accuracy: 0.5064
Epoch 66/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6960 - val_accuracy: 0.5064
Epoch 67/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 68/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6957 - val_accuracy: 0.5064
Epoch 69/80
751/751 [==============================] - 4s 5ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6965 - val_accuracy: 0.5064
Epoch 70/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 71/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6955 - val_accuracy: 0.5064
Epoch 72/80
751/751 [==============================] - 3s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6962 - val_accuracy: 0.5064
Epoch 73/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6961 - val_accuracy: 0.5064
Epoch 74/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6960 - val_accuracy: 0.5064
Epoch 75/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6962 - val_accuracy: 0.5064
Epoch 76/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6958 - val_accuracy: 0.5064
Epoch 77/80
751/751 [==============================] - 2s 3ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6959 - val_accuracy: 0.5064
Epoch 78/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 79/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6956 - val_accuracy: 0.5064
Epoch 80/80
751/751 [==============================] - 3s 4ms/step - loss: 0.6894 - accuracy: 0.5435 - val_loss: 0.6961 - val_accuracy: 0.5064

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [70]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 3.3670 - accuracy: 0.4805 - 359ms/epoch - 1ms/step
Loss: 3.367025852203369, Accuracy: 0.48046648502349854

In [71]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 8.1631 - accuracy: 0.4708 - 605ms/epoch - 2ms/step
Loss: 8.163082122802734, Accuracy: 0.4707871675491333

In [73]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.6920 - accuracy: 0.5292 - 541ms/epoch - 2ms/step
Loss: 0.6919742226600647, Accuracy: 0.5292128324508667

### Step 3: Save each of your alternative models as an HDF5 file.

In [77]:
# Set the file path for the first alternative model
file_path = "/content/applicants_data.h5"

# Export your model to a HDF5 file
nn_1 = tf.keras.models.load_model(file_path)

In [79]:
# Set the file path for the second alternative model
file_path = "/content/applicants_data.h5"

# Export your model to a HDF5 file
nn_2 = tf.keras.models.load_model(file_path)